#!/usr/bin/env bash

if [ $# -lt 1 ]; then
  echo "Usage $0 <casePattern>"
  exit 1
fi

. scripts/common.sh

CASE_PATTERN="$1"
CASE_SOURCE="cases/${CASE_PATTERN}/run/"
EXIT_VALUES=0

echo "Looking at $CASE_SOURCE"

FIND_RESULTS=$( find $CASE_SOURCE -name 'LAST_EXIT' )
FIND_EXIT=$?

if [ $FIND_EXIT == 1 ]; then exit 0; fi

for EXIT_FILE in $FIND_RESULTS; do
  EXIT_STATUS=`cat $EXIT_FILE`
  echo "$EXIT_FILE has exit status $EXIT_STATUS"

  if [ $EXIT_STATUS -ne 0 ] && [ $EXIT_STATUS -ne 124 ]; then
    echo "Non-timeout status $EXIT_STATUS changing to 0"
    EXIT_STATUS=0
  fi
  EXIT_VALUES=`expr $EXIT_VALUES \+ $EXIT_STATUS`
done

TIMEOUT_STATUSES=`expr $EXIT_VALUES / 124`
echo "Timeout statuses: $TIMEOUT_STATUSES"

if [ $TIMEOUT_STATUSES -gt 0 ]; then
  exit 1
fi

exit 0
