#!/usr/bin/env bash

if [ $# -lt 1 ]; then
  echo "Usage $0 <name>"
  exit 1
fi

. scripts/common.sh

NAME="$1"

RUNDIR="cases/$NAME/run"

if [ ! -d $RUNDIR ]; then
  echo "Missing run directory, is the case created?: $RUNDIR"
  exit 1
fi

cd $RUNDIR
export PATH="`realpath ..`/scripts:$PATH"

prep_run

timeout 10 run_driver

RETCODE=$?
echo "Julia process returned: $RETCODE"

exit $RETCODE
