#!/usr/bin/env bash

if [ $# -lt 1 ]; then
  echo "Usage $0 <name> [copy_from]"
  exit 1
fi

. scripts/common.sh

NAME="$1"
COPY_FROM="${2:-template}"

if [ -d "cases/$NAME" ]; then
  echo "$NAME already exists, abandoning"
  exit 1
fi

cp -RLv cases/$COPY_FROM cases/$NAME
ln -s cases/$NAME/input/driver.jl cases/$NAME/input/driver.jl.j2
ln -s cases/$NAME/scripts/run_ensemble_member cases/$NAME/input/run_ensemble_member.j2
