#!/usr/bin/bash

if [ ! -d venv ]; then
  if [ $( python3 --version 2>&1 | sed -r 's/^.+ 3\.([0-9]+)\..+$/\1/' ) -lt 7 ]; then
    echo "You need to be running python3 at least of version 3.7"
    exit 1
  fi

  echo "Setting up a python environment for model ensembler"
  python3 -m venv venv
  source venv/bin/activate

  pip install --upgrade pip setuptools
  pip install model_ensembler
else
  source venv/bin/activate
fi

CFG_DIR="`dirname $0`"
ENSEMBLE_TARGET="slurm"
ENSEMBLE_NAME="${1:-local_ensemble}"
ENSEMBLE_TYPE="`basename $CFG_DIR`"

if [ "$ENSEMBLE_TYPE" == "local" ]; then
  ENSEMBLE_TARGET="dummy"
fi

sed -r "s/NAME/${ENSEMBLE_NAME}/g" \
  scripts/$ENSEMBLE_TYPE/ensemble.yaml >${ENSEMBLE_NAME}.yaml

until check_timeout_statuses "local_ensemble-*"; do
  echo "Running another ensemble, individual runs timed out"
  model_ensemble -p -v ${ENSEMBLE_NAME}.yaml $ENSEMBLE_TARGET
done

exit $?
